//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idp.Domain._Shared.Resources.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusinessExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Idp.Domain._Shared.Resources.Exceptions.BusinessExceptions", typeof(BusinessExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or phone number format is not correct..
        /// </summary>
        internal static string EmailOrPhoneNumberFormatIsNotCorrect {
            get {
                return ResourceManager.GetString("EmailOrPhoneNumberFormatIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For confirmation, the user must have an email..
        /// </summary>
        internal static string ForConfirmationTheUserMustHaveAnEmail {
            get {
                return ResourceManager.GetString("ForConfirmationTheUserMustHaveAnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For confirmation, the user must have a phone number..
        /// </summary>
        internal static string ForConfirmationTheUserMustHaveAPhoneNumber {
            get {
                return ResourceManager.GetString("ForConfirmationTheUserMustHaveAPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email format is not correct..
        /// </summary>
        internal static string TheEmailFormatIsNotCorrect {
            get {
                return ResourceManager.GetString("TheEmailFormatIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number format is not correct..
        /// </summary>
        internal static string ThePhoneNumberFormatIsNotCorrect {
            get {
                return ResourceManager.GetString("ThePhoneNumberFormatIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user must have at least one email or one phone number..
        /// </summary>
        internal static string TheUserMustHaveAtLeastOneEmailOrOnePhoneNumber {
            get {
                return ResourceManager.GetString("TheUserMustHaveAtLeastOneEmailOrOnePhoneNumber", resourceCulture);
            }
        }
    }
}
