<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Framework\Framework.Infrastructure\Framework.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Framework\Framework.Presentation\Framework.Presentation.csproj" />
    <ProjectReference Include="..\Idp.Application\Idp.Application.csproj" />
    <ProjectReference Include="..\Idp.Domain\Idp.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="_Shared\Resources\ApiValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ApiValidationMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="_Shared\Resources\ApiValidationMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ApiValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
